Resources:
  User:
    Type: AWS::Serverless::Function
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: /user
      Handler: index.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          NODE_OPTIONS: '--enable-source-maps'
      MemorySize: 3008
      Timeout: 30
      Architectures:
        - arm64
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build-typescript.html
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        Minify: false # Specifies whether to minify the bundled output code. The default value is true.
        #Specifies the list of packages to omit from the build
        # External:
        #   - "<package-to-exclude>"